name: hdbrts
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  badges: ^2.0.1
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.18
  stripe_payment: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
